{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "05224ae7-1e4c-4e11-b581-36c50f640f68",
   "metadata": {},
   "outputs": [],
   "source": [
    "import rdkit\n",
    "from rdkit import Chem\n",
    "from rdkit.Chem import Descriptors\n",
    "from rdkit.ML.Descriptors.MoleculeDescriptors import MolecularDescriptorCalculator\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "def peptide_to_charged_smiles(sequence: str) -> str:\n",
    "    \"\"\"\n",
    "    Convert peptide sequence to charged SMILES representation.\n",
    "    N-terminus is protonated ([NH3+])\n",
    "    C-terminus is deprotonated ([O-])\n",
    "    \"\"\"\n",
    "\n",
    "    amino_acid_smiles = {\n",
    "        'A': 'N[C@@H](C)C(=O)',\n",
    "        'R': 'N[C@@H](CCCNC([NH3+])=N)C(=O)',\n",
    "        'N': 'N[C@@H](CC(=O)N)C(=O)',\n",
    "        'D': 'N[C@@H](CC(=O)[O-])C(=O)',\n",
    "        'C': 'N[C@@H](CS)C(=O)',\n",
    "        'E': 'N[C@@H](CCC(=O)[O-])C(=O)',\n",
    "        'Q': 'N[C@@H](CCC(=O)N)C(=O)',\n",
    "        'G': 'NCC(=O)',\n",
    "        'H': 'N[C@@H](CC1=CN=CN1)C(=O)',\n",
    "        'I': 'N[C@@H](C(C)CC)C(=O)',\n",
    "        'L': 'N[C@@H](CC(C)C)C(=O)',\n",
    "        'K': 'N[C@@H](CCCC[NH3+])C(=O)',\n",
    "        'M': 'N[C@@H](CCSC)C(=O)',\n",
    "        'F': 'N[C@@H](Cc1ccccc1)C(=O)',\n",
    "        'P': 'N1[C@H](CCC1)C(=O)',\n",
    "        'S': 'N[C@@H](CO)C(=O)',\n",
    "        'T': 'N[C@@H](C(O)C)C(=O)',\n",
    "        'W': 'N[C@@H](Cc1c[nH]c2c1cccc2)C(=O)',\n",
    "        'Y': 'N[C@@H](Cc1ccc(O)cc1)C(=O)',\n",
    "        'V': 'N[C@@H](C(C)C)C(=O)'\n",
    "    }\n",
    "\n",
    "    amino_acid_smiles_n_ter = {\n",
    "        'A': '[NH3+][C@@H](C)C(=O)',\n",
    "        'R': '[NH3+][C@@H](CCCNC([NH3+])=N)C(=O)',\n",
    "        'N': '[NH3+][C@@H](CC(=O)N)C(=O)',\n",
    "        'D': '[NH3+][C@@H](CC(=O)[O-])C(=O)',\n",
    "        'C': '[NH3+][C@@H](CS)C(=O)',\n",
    "        'E': '[NH3+][C@@H](CCC(=O)[O-])C(=O)',\n",
    "        'Q': '[NH3+][C@@H](CCC(=O)N)C(=O)',\n",
    "        'G': '[NH3+]CC(=O)',\n",
    "        'H': '[NH3+][C@@H](CC1=CN=CN1)C(=O)',\n",
    "        'I': '[NH3+][C@@H](C(C)CC)C(=O)',\n",
    "        'L': '[NH3+][C@@H](CC(C)C)C(=O)',\n",
    "        'K': '[NH3+][C@@H](CCCC[NH3+])C(=O)',\n",
    "        'M': '[NH3+][C@@H](CCSC)C(=O)',\n",
    "        'F': '[NH3+][C@@H](Cc1ccccc1)C(=O)',\n",
    "        'P': '[NH2+]1[C@H](CCC1)C(=O)',\n",
    "        'S': '[NH3+][C@@H](CO)C(=O)',\n",
    "        'T': '[NH3+][C@@H](C(O)C)C(=O)',\n",
    "        'W': '[NH3+][C@@H](Cc1c[nH]c2c1cccc2)C(=O)',\n",
    "        'Y': '[NH3+][C@@H](Cc1ccc(O)cc1)C(=O)',\n",
    "        'V': '[NH3+][C@@H](C(C)C)C(=O)'\n",
    "    }\n",
    "\n",
    "    smiles = \"\"\n",
    "\n",
    "    for i, aa in enumerate(sequence):\n",
    "\n",
    "        if aa not in amino_acid_smiles:\n",
    "            raise ValueError(f\"Unknown amino acid: {aa}\")\n",
    "\n",
    "        if i == 0:\n",
    "            smiles += amino_acid_smiles_n_ter[aa]\n",
    "        else:\n",
    "            smiles += amino_acid_smiles[aa]\n",
    "\n",
    "    # Add charged C-terminus\n",
    "    smiles += '[O-]'\n",
    "\n",
    "    return smiles\n",
    "\n",
    "\n",
    "def smiles_to_descriptors(smiles: str,\n",
    "                          calc,\n",
    "                          desc_names):\n",
    "    \"\"\"\n",
    "    Calculate RDKit descriptors from SMILES.\n",
    "    Invalid SMILES -> NaN values.\n",
    "    \"\"\"\n",
    "\n",
    "    if not isinstance(smiles, str) or not smiles.strip():\n",
    "        return {n: np.nan for n in desc_names}\n",
    "\n",
    "    mol = Chem.MolFromSmiles(smiles)\n",
    "\n",
    "    if mol is None:\n",
    "        return {n: np.nan for n in desc_names}\n",
    "\n",
    "    try:\n",
    "        vals = calc.CalcDescriptors(mol)\n",
    "        return dict(zip(desc_names, vals))\n",
    "\n",
    "    except Exception:\n",
    "        return {n: np.nan for n in desc_names}\n",
    "\n",
    "\n",
    "def build_peptide_global_descriptors(df: pd.DataFrame,\n",
    "                                     seq_col: str = \"seq\",\n",
    "                                     drop_cols: list = [\"Ipc\"]):\n",
    "    \"\"\"\n",
    "    Full pipeline:\n",
    "    peptide sequence -> charged SMILES -> RDKit descriptors\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    df : pd.DataFrame\n",
    "        Input dataframe containing peptide sequences\n",
    "\n",
    "    seq_col : str\n",
    "        Column name containing peptide sequences\n",
    "\n",
    "    drop_cols : list\n",
    "        Descriptor columns to remove\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    pd.DataFrame\n",
    "        Original dataframe + SMILES + descriptors\n",
    "    \"\"\"\n",
    "\n",
    "    peptides = df.copy()\n",
    "\n",
    "    # Convert sequences to charged SMILES\n",
    "    peptides[\"smiles\"] = peptides[seq_col].apply(\n",
    "        peptide_to_charged_smiles\n",
    "    )\n",
    "\n",
    "    # Descriptor names\n",
    "    desc_names = [name for name, _ in Descriptors.descList]\n",
    "\n",
    "    # Calculator\n",
    "    calc = MolecularDescriptorCalculator(desc_names)\n",
    "\n",
    "    # Calculate descriptors\n",
    "    desc = peptides[\"smiles\"].apply(\n",
    "        lambda x: smiles_to_descriptors(x, calc, desc_names)\n",
    "    ).apply(pd.Series)\n",
    "\n",
    "    # Drop unwanted descriptors\n",
    "    desc = desc.drop(columns=drop_cols, errors=\"ignore\")\n",
    "\n",
    "    # Combine\n",
    "    final_df = pd.concat(\n",
    "        [peptides.reset_index(drop=True),\n",
    "         desc.reset_index(drop=True)],\n",
    "        axis=1\n",
    "    )\n",
    "\n",
    "    return final_df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
