{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "11f08f60-d3f6-4f12-8ee1-3ce5e36727eb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def standard_scaling(train_set, test_set):\n",
    "    scaler = StandardScaler().fit(train_set)\n",
    "    #Scaling the datasets\n",
    "    train_set_scaled = scaler.transform(train_set)\n",
    "    test_set_scaled = scaler.transform(test_set)\n",
    "    #Create dataframes with the correct index\n",
    "    train_set_scaled = pd.DataFrame(train_set_scaled, index=train_set.index, columns=train_set.columns)\n",
    "    test_set_scaled = pd.DataFrame(test_set_scaled, index=test_set.index, columns=test_set.columns)\n",
    "    return train_set_scaled, test_set_scaled\n",
    "\n",
    "def reg_results_df(trained_model, X_train, X_test, y_train, y_test):\n",
    "\n",
    "    #Predictions\n",
    "    y_train_pred = trained_model.predict(X_train).flatten()\n",
    "    y_test_pred = trained_model.predict(X_test).flatten()\n",
    "\n",
    "    print(\"train:\")\n",
    "    print(confusion_matrix(y_train, y_train_pred))\n",
    "    print(classification_report(y_train, y_train_pred))\n",
    "    \n",
    "    print(\"test\")\n",
    "    print( confusion_matrix(y_test, y_test_pred))\n",
    "    print(classification_report(y_test, y_test_pred))\n",
    "    accuracy = accuracy_score(y_test, y_test_pred)\n",
    "    print(f'Accuracy: {accuracy:.4f}')\n",
    "    print(trained_model.score(X_test, y_test))\n",
    "\n",
    "def outlier_removal(scaled_train, scaled_test, contamination):\n",
    "    clf = IsolationForest(random_state=42, n_estimators=100, max_samples='auto', contamination=contamination, n_jobs=1).fit(scaled_train)\n",
    "    x_train_outliers = clf.predict(scaled_train) #Returns -1 for outliers and 1 for inliers\n",
    "    x_test_outliers = clf.predict(scaled_test)\n",
    "\n",
    "    X_train_clean = pd.concat([scaled_train, pd.DataFrame(data=x_train_outliers, columns=['Outlier_prediction'], index=scaled_train.index )], axis=1, join='inner' )\n",
    "    X_train_clean = X_train_clean.drop( X_train_clean[X_train_clean['Outlier_prediction'] == -1].index, axis=0) \n",
    "    X_train_clean = X_train_clean.drop('Outlier_prediction', axis=1)  \n",
    "\n",
    "    X_test_clean = pd.concat([scaled_test, pd.DataFrame(data=x_test_outliers, columns=['Outlier_prediction'], index=scaled_test.index )], axis=1, join='inner' )\n",
    "    X_test_clean = X_test_clean.drop( X_test_clean[X_test_clean['Outlier_prediction'] == -1].index, axis=0) \n",
    "    X_test_clean = X_test_clean.drop('Outlier_prediction', axis=1)\n",
    "\n",
    "    n_outliers_train = len(scaled_train) - len(X_train_clean)\n",
    "    n_outliers_test = len(scaled_test) - len(X_test_clean)\n",
    "\n",
    "    print('Performing outlier removal:')\n",
    "\n",
    "    print('the number of outliers for the train set is:', n_outliers_train) \n",
    "    print('the number of outliers for the test set is:', n_outliers_test)\n",
    "    \n",
    "    return X_train_clean, X_test_clean\n",
    "\n",
    "def feature_reduction(train_set, test_set, var_threshold=0.05, corr_threshold=0.8):\n",
    "    print('Number of features originally: ', len(train_set.columns))\n",
    "    print(\"Removing Constant and Nearly Constant Features\")\n",
    "    var_threshold = VarianceThreshold(threshold=var_threshold)\n",
    "    var_threshold.fit(train_set)\n",
    "\n",
    "    indices_features_retained = var_threshold.get_support(indices=True)\n",
    "    train_set_reduced1 = train_set.iloc[:, indices_features_retained]\n",
    "\n",
    "    print('Features retained after elimination of constant and nearly constant features:', len(train_set_reduced1.columns))\n",
    "\n",
    "    print(\"Removing Correlated Features\")\n",
    "\n",
    "    # Calculate the correlation matrix\n",
    "    corr_matrix = train_set_reduced1.corr()\n",
    "    iters = range(len(corr_matrix.columns) - 1)\n",
    "    drop_cols = []\n",
    "\n",
    "    # Iterate through the correlation matrix and compare correlations\n",
    "    for i in iters:\n",
    "        for j in range(i+1):\n",
    "            item = corr_matrix.iloc[j:(j+1), (i+1):(i+2)]\n",
    "            col = item.columns\n",
    "            row = item.index\n",
    "            val = abs(item.values)\n",
    "\n",
    "            # If correlation exceeds the threshold\n",
    "            if val >= corr_threshold:\n",
    "                # Print the correlated features and the correlation value\n",
    "                print(col.values[0], \"|\", row.values[0], \"|\", round(val[0][0], 2))\n",
    "                drop_cols.append(col.values[0])\n",
    "\n",
    "    # Drop one of each pair of correlated columns\n",
    "    drops = set(drop_cols)\n",
    "    train_set_reduced2 = train_set_reduced1.drop(columns=drops)\n",
    "    print('Removed Columns {}'.format(drops))\n",
    "    print('Number of features retained: ', len(train_set_reduced2.columns))\n",
    "\n",
    "    test_set_reduced = test_set[train_set_reduced2.columns]\n",
    "\n",
    "    return train_set_reduced2, test_set_reduced\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.metrics import (\n",
    "    confusion_matrix,\n",
    "    f1_score,\n",
    "    matthews_corrcoef,\n",
    "    roc_auc_score,\n",
    "    accuracy_score,\n",
    ")\n",
    "\n",
    "def show_classification_metrics(model, X_train, X_test, y_train, y_test,\n",
    "                                pos_label=1):\n",
    "    \"\"\"\n",
    "    model : fitted sklearn classifier\n",
    "    pos_label : which label is considered \"positive\" (default = 1)\n",
    "    \"\"\"\n",
    "\n",
    "    # helper: compute metrics for one split\n",
    "    def compute_metrics(y_true, y_pred, y_score):\n",
    "        tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()\n",
    "\n",
    "        sensitivity = tp / (tp + fn) if (tp + fn) > 0 else np.nan   # recall+\n",
    "        specificity = tn / (tn + fp) if (tn + fp) > 0 else np.nan\n",
    "        f1 = f1_score(y_true, y_pred, pos_label=pos_label)\n",
    "        mcc = matthews_corrcoef(y_true, y_pred)\n",
    "        roc = roc_auc_score(y_true, y_score)\n",
    "        acc = accuracy_score(y_true, y_pred)\n",
    "\n",
    "        return {\n",
    "            \"Accuracy\": acc,\n",
    "            \"Sensitivity\": sensitivity,\n",
    "            \"Specificity\": specificity,\n",
    "            \"F1\": f1,\n",
    "            \"MCC\": mcc,\n",
    "            \"ROC_AUC\": roc,\n",
    "        }\n",
    "\n",
    "    # scores for ROC\n",
    "    if hasattr(model, \"predict_proba\"):\n",
    "        y_train_score = model.predict_proba(X_train)[:, 1]\n",
    "        y_test_score  = model.predict_proba(X_test)[:, 1]\n",
    "    else:\n",
    "        # e.g. SVM with decision_function\n",
    "        y_train_score = model.decision_function(X_train)\n",
    "        y_test_score  = model.decision_function(X_test)\n",
    "\n",
    "    # hard predictions\n",
    "    y_train_pred = model.predict(X_train)\n",
    "    y_test_pred  = model.predict(X_test)\n",
    "\n",
    "    train_metrics = compute_metrics(y_train, y_train_pred, y_train_score)\n",
    "    test_metrics  = compute_metrics(y_test,  y_test_pred,  y_test_score)\n",
    "\n",
    "    results_df = pd.DataFrame([train_metrics, test_metrics],\n",
    "                              index=[\"Train\", \"Test\"])\n",
    "    print(results_df.round(3))\n",
    "    return results_df\n",
    "\n",
    "def evaluate_classification_models_random_splits(\n",
    "    models_dict,\n",
    "    X,\n",
    "    y,\n",
    "    splits,\n",
    "    target,\n",
    "    scale,\n",
    "    pos_label=1\n",
    "):\n",
    "\n",
    "\n",
    "    rows = []\n",
    "\n",
    "    for model_name, base_model in models_dict.items():\n",
    "        # Lists per model\n",
    "        acc_train_list, sens_train_list, spec_train_list = [], [], []\n",
    "        f1_train_list, mcc_train_list, auc_train_list = [], [], []\n",
    "\n",
    "        acc_test_list, sens_test_list, spec_test_list = [], [], []\n",
    "        f1_test_list, mcc_test_list, auc_test_list = [], [], []\n",
    "\n",
    "        for train_idx, test_idx in splits:\n",
    "            # Handle pandas or numpy\n",
    "            if hasattr(X, \"iloc\"):\n",
    "                X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]\n",
    "            else:\n",
    "                X_train, X_test = X[train_idx], X[test_idx]\n",
    "\n",
    "            if hasattr(y, \"iloc\"):\n",
    "                y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]\n",
    "            else:\n",
    "                y_train, y_test = y[train_idx], y[test_idx]\n",
    "\n",
    "            # IMPORTANT: clone the model so each split starts from a fresh estimator\n",
    "            model = clone(base_model)\n",
    "\n",
    "            # Combine into train/test sets (for your feature_reduction / outlier_removal)\n",
    "            train_set = pd.concat([X_train, y_train], axis=1)\n",
    "            test_set = pd.concat([X_test, y_test], axis=1)\n",
    "\n",
    "            # standard scaling (your custom function)\n",
    "            X_train=train_set.drop(target,axis=1)\n",
    "            y_train=train_set[target]\n",
    "            X_test=test_set.drop(target,axis=1)\n",
    "            y_test=test_set[target]\n",
    "            if scale:\n",
    "                X_train, X_test = standard_scaling(X_train, X_test)\n",
    "\n",
    "                train_set=pd.concat([X_train,y_train],axis=1)\n",
    "                test_set=pd.concat([X_test,y_test],axis=1)\n",
    "            \n",
    "            # remove correlated features (your custom function)\n",
    "            train_set_reduced, test_set_reduced = feature_reduction(\n",
    "                train_set,\n",
    "                test_set,\n",
    "                var_threshold=0.05,\n",
    "                corr_threshold=0.8\n",
    "            )\n",
    "\n",
    "            # remove outliers (your custom function)\n",
    "            train_clean, test_clean = outlier_removal(\n",
    "                train_set_reduced,\n",
    "                test_set_reduced,\n",
    "                contamination=0.15\n",
    "            )\n",
    "\n",
    "            # split X, y again\n",
    "            X_train = train_clean.drop(target, axis=1)\n",
    "            y_train = train_clean[target]\n",
    "            X_test = test_clean.drop(target, axis=1)\n",
    "            y_test = test_clean[target]\n",
    "\n",
    "            \n",
    "            # ---- Fit on train ----\n",
    "            model.fit(X_train, y_train)\n",
    "\n",
    "            # =======================\n",
    "            #       TRAIN METRICS\n",
    "            # =======================\n",
    "            y_pred_train = model.predict(X_train)\n",
    "\n",
    "            acc_train = accuracy_score(y_train, y_pred_train)\n",
    "            sens_train = recall_score(y_train, y_pred_train, pos_label=pos_label)\n",
    "\n",
    "            # Specificity = recall of the negative class\n",
    "            tn, fp, fn, tp = confusion_matrix(y_train, y_pred_train, labels=[0, 1]).ravel()\n",
    "            spec_train = tn / (tn + fp) if (tn + fp) > 0 else np.nan\n",
    "\n",
    "            f1_tr = f1_score(y_train, y_pred_train, pos_label=pos_label)\n",
    "            mcc_tr = matthews_corrcoef(y_train, y_pred_train)\n",
    "\n",
    "            # ROC AUC on train\n",
    "            try:\n",
    "                if hasattr(model, \"predict_proba\"):\n",
    "                    y_score_tr = model.predict_proba(X_train)[:, 1]\n",
    "                else:\n",
    "                    y_score_tr = model.decision_function(X_train)\n",
    "                auc_tr = roc_auc_score(y_train, y_score_tr)\n",
    "            except Exception:\n",
    "                auc_tr = np.nan\n",
    "\n",
    "            acc_train_list.append(acc_train)\n",
    "            sens_train_list.append(sens_train)\n",
    "            spec_train_list.append(spec_train)\n",
    "            f1_train_list.append(f1_tr)\n",
    "            mcc_train_list.append(mcc_tr)\n",
    "            auc_train_list.append(auc_tr)\n",
    "\n",
    "            # =======================\n",
    "            #       TEST METRICS\n",
    "            # =======================\n",
    "            y_pred_test = model.predict(X_test)\n",
    "\n",
    "            acc_test = accuracy_score(y_test, y_pred_test)\n",
    "            sens_test = recall_score(y_test, y_pred_test, pos_label=pos_label)\n",
    "\n",
    "            tn, fp, fn, tp = confusion_matrix(y_test, y_pred_test, labels=[0, 1]).ravel()\n",
    "            spec_test = tn / (tn + fp) if (tn + fp) > 0 else np.nan\n",
    "\n",
    "            f1_te = f1_score(y_test, y_pred_test, pos_label=pos_label)\n",
    "            mcc_te = matthews_corrcoef(y_test, y_pred_test)\n",
    "\n",
    "            # ROC AUC on test\n",
    "            try:\n",
    "                if hasattr(model, \"predict_proba\"):\n",
    "                    y_score_te = model.predict_proba(X_test)[:, 1]\n",
    "                else:\n",
    "                    y_score_te = model.decision_function(X_test)\n",
    "                auc_te = roc_auc_score(y_test, y_score_te)\n",
    "            except Exception:\n",
    "                auc_te = np.nan\n",
    "\n",
    "            acc_test_list.append(acc_test)\n",
    "            sens_test_list.append(sens_test)\n",
    "            spec_test_list.append(spec_test)\n",
    "            f1_test_list.append(f1_te)\n",
    "            mcc_test_list.append(mcc_te)\n",
    "            auc_test_list.append(auc_te)\n",
    "\n",
    "        # After all splits for this model: compute mean & std\n",
    "\n",
    "        # Train row\n",
    "        rows.append({\n",
    "            \"Model\": model_name,\n",
    "            \"Set\": \"Train\",\n",
    "            \"Accuracy_mean\": np.mean(acc_train_list),\n",
    "            \"Accuracy_std\":  np.std(acc_train_list),\n",
    "            \"Sensitivity_mean\": np.mean(sens_train_list),\n",
    "            \"Sensitivity_std\":  np.std(sens_train_list),\n",
    "            \"Specificity_mean\": np.mean(spec_train_list),\n",
    "            \"Specificity_std\":  np.std(spec_train_list),\n",
    "            \"F1_mean\": np.mean(f1_train_list),\n",
    "            \"F1_std\":  np.std(f1_train_list),\n",
    "            \"MCC_mean\": np.mean(mcc_train_list),\n",
    "            \"MCC_std\":  np.std(mcc_train_list),\n",
    "            \"ROC_AUC_mean\": np.mean(auc_train_list),\n",
    "            \"ROC_AUC_std\":  np.std(auc_train_list),\n",
    "        })\n",
    "\n",
    "        # Test row\n",
    "        rows.append({\n",
    "            \"Model\": model_name,\n",
    "            \"Set\": \"Test\",\n",
    "            \"Accuracy_mean\": np.mean(acc_test_list),\n",
    "            \"Accuracy_std\":  np.std(acc_test_list),\n",
    "            \"Sensitivity_mean\": np.mean(sens_test_list),\n",
    "            \"Sensitivity_std\":  np.std(sens_test_list),\n",
    "            \"Specificity_mean\": np.mean(spec_test_list),\n",
    "            \"Specificity_std\":  np.std(spec_test_list),\n",
    "            \"F1_mean\": np.mean(f1_test_list),\n",
    "            \"F1_std\":  np.std(f1_test_list),\n",
    "            \"MCC_mean\": np.mean(mcc_test_list),\n",
    "            \"MCC_std\":  np.std(mcc_test_list),\n",
    "            \"ROC_AUC_mean\": np.mean(auc_test_list),\n",
    "            \"ROC_AUC_std\":  np.std(auc_test_list),\n",
    "        })\n",
    "\n",
    "    results_df = pd.DataFrame(rows)\n",
    "    return results_df\n",
    "\n",
    "def run_classification_model(\n",
    "        model_name,\n",
    "        X_train,\n",
    "        X_test,\n",
    "        y_train,\n",
    "        y_test,\n",
    "        cv=5,\n",
    "        scoring=\"accuracy\",\n",
    "        n_jobs=-1,\n",
    "        verbose=2,\n",
    "        pos_label=1\n",
    "):\n",
    "    \"\"\"\n",
    "    Train classification model with GridSearchCV.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    model_name : str\n",
    "\n",
    "        One of:\n",
    "        - 'logistic_regression'\n",
    "        - 'random_forest'\n",
    "        - 'decision_tree'\n",
    "        - 'xgboost'\n",
    "        - 'knn'\n",
    "        - 'svm'\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    best_model\n",
    "    results_df\n",
    "    \"\"\"\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # Logistic Regression\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    if model_name == \"logistic_regression\":\n",
    "\n",
    "        model = LogisticRegression(\n",
    "            solver='liblinear',\n",
    "            max_iter=1000\n",
    "        )\n",
    "\n",
    "        param_grid = {\n",
    "            'penalty': ['l2'],\n",
    "            'C': [0.01, 0.1, 1, 10, 100]\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # Random Forest\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"random_forest\":\n",
    "\n",
    "        model = RandomForestClassifier(\n",
    "            random_state=42\n",
    "        )\n",
    "\n",
    "        param_grid = {\n",
    "            'n_estimators': [100, 200],\n",
    "            'max_depth': [None, 3, 5, 10, 20],\n",
    "            'min_samples_split': [2, 5],\n",
    "            'min_samples_leaf': [1, 2],\n",
    "            'max_features': ['sqrt', 'log2']\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # Decision Tree\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"decision_tree\":\n",
    "\n",
    "        model = DecisionTreeClassifier(\n",
    "            random_state=42\n",
    "        )\n",
    "\n",
    "        param_grid = {\n",
    "            'criterion': ['gini', 'entropy'],\n",
    "            'max_depth': [None, 5, 10, 20],\n",
    "            'min_samples_split': [2, 5, 10],\n",
    "            'min_samples_leaf': [1, 2, 4],\n",
    "            'max_features': [None, 'sqrt', 'log2']\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # XGBoost\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"xgboost\":\n",
    "\n",
    "        model = XGBClassifier(\n",
    "            random_state=42,\n",
    "            eval_metric='logloss'\n",
    "        )\n",
    "\n",
    "        param_grid = {\n",
    "            'n_estimators': [100, 200],\n",
    "            'max_depth': [3, 6, 10],\n",
    "            'learning_rate': [0.01, 0.1, 0.2],\n",
    "            'subsample': [0.8, 1.0],\n",
    "            'colsample_bytree': [0.8, 1.0],\n",
    "            'gamma': [0, 1, 5]\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # KNN\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"knn\":\n",
    "\n",
    "        model = KNeighborsClassifier()\n",
    "\n",
    "        param_grid = {\n",
    "            'n_neighbors': [3, 5, 7, 9],\n",
    "            'weights': ['uniform', 'distance'],\n",
    "            'p': [1, 2]\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # SVM\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"svm\":\n",
    "\n",
    "        model = SVC()\n",
    "\n",
    "        param_grid = {\n",
    "            'C': [0.1, 1, 10],\n",
    "            'kernel': ['linear', 'rbf', 'poly'],\n",
    "            'gamma': ['scale', 'auto']\n",
    "        }\n",
    "\n",
    "    else:\n",
    "        raise ValueError(f\"Unknown model_name: {model_name}\")\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # GridSearchCV\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    grid_search = GridSearchCV(\n",
    "        estimator=model,\n",
    "        param_grid=param_grid,\n",
    "        cv=cv,\n",
    "        scoring=scoring,\n",
    "        n_jobs=n_jobs,\n",
    "        verbose=verbose\n",
    "    )\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # Fit model\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    grid_search.fit(X_train, y_train)\n",
    "\n",
    "    best_model = grid_search.best_estimator_\n",
    "\n",
    "    print(\"Best model:\")\n",
    "    print(best_model)\n",
    "\n",
    "    print(\"\\nBest parameters:\")\n",
    "    print(grid_search.best_params_)\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # Optional regression-style plot\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    try:\n",
    "\n",
    "        reg_results_df(\n",
    "            grid_search,\n",
    "            X_train,\n",
    "            X_test,\n",
    "            y_train,\n",
    "            y_test\n",
    "        )\n",
    "\n",
    "    except:\n",
    "        pass\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # Classification metrics\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    results_df = show_classification_metrics(\n",
    "        best_model,\n",
    "        X_train,\n",
    "        X_test,\n",
    "        y_train,\n",
    "        y_test,\n",
    "        pos_label=pos_label\n",
    "    )\n",
    "\n",
    "    return best_model, results_df\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
