{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c5c6b87-393c-4339-afb1-e2ee8bca241f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.decomposition import PCA\n",
    "\n",
    "\n",
    "def build_peptide_pca_descriptors(\n",
    "        peptides_df: pd.DataFrame,\n",
    "        c_des_path: str,\n",
    "        n_des_path: str,\n",
    "        uncharged_des_path: str,\n",
    "        seq_col: str = \"seq\",\n",
    "        n_components: int = 3\n",
    "):\n",
    "    \"\"\"\n",
    "    Build amino-acid PCA descriptor representation for peptide sequences.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    peptides_df : pd.DataFrame\n",
    "        DataFrame containing peptide sequences.\n",
    "\n",
    "    c_des_path : str\n",
    "        Path to C-terminus descriptor CSV.\n",
    "\n",
    "    n_des_path : str\n",
    "        Path to N-terminus descriptor CSV.\n",
    "\n",
    "    uncharged_des_path : str\n",
    "        Path to uncharged amino acid descriptor CSV.\n",
    "\n",
    "    seq_col : str\n",
    "        Column containing peptide sequences.\n",
    "\n",
    "    n_components : int\n",
    "        Number of PCA components.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    pd.DataFrame\n",
    "        Original dataframe + PCA sequence descriptors.\n",
    "    \"\"\"\n",
    "\n",
    "    # -----------------------------\n",
    "    # Load descriptor tables\n",
    "    # -----------------------------\n",
    "\n",
    "    c_des = pd.read_csv(c_des_path)\n",
    "    n_des = pd.read_csv(n_des_path)\n",
    "    uncharged_des = pd.read_csv(uncharged_des_path)\n",
    "\n",
    "    # Remove SMILES column if exists\n",
    "    c_des = c_des.drop(columns=[\"SMILES\"], errors=\"ignore\")\n",
    "    n_des = n_des.drop(columns=[\"SMILES\"], errors=\"ignore\")\n",
    "    uncharged_des = uncharged_des.drop(columns=[\"SMILES\"], errors=\"ignore\")\n",
    "\n",
    "    # -----------------------------\n",
    "    # Scale descriptors\n",
    "    # -----------------------------\n",
    "\n",
    "    scaler = StandardScaler()\n",
    "\n",
    "    c_scaled = scaler.fit_transform(c_des.drop(\"AA\", axis=1))\n",
    "    n_scaled = scaler.fit_transform(n_des.drop(\"AA\", axis=1))\n",
    "    uncharged_scaled = scaler.fit_transform(\n",
    "        uncharged_des.drop(\"AA\", axis=1)\n",
    "    )\n",
    "\n",
    "    # -----------------------------\n",
    "    # PCA\n",
    "    # -----------------------------\n",
    "\n",
    "    pca_c = PCA(n_components=n_components)\n",
    "    pca_n = PCA(n_components=n_components)\n",
    "    pca_uncharged = PCA(n_components=n_components)\n",
    "\n",
    "    c_pca = pca_c.fit_transform(c_scaled)\n",
    "    n_pca = pca_n.fit_transform(n_scaled)\n",
    "    uncharged_pca = pca_uncharged.fit_transform(uncharged_scaled)\n",
    "\n",
    "    # PCA DataFrames\n",
    "    pc_cols = [f\"PC{i+1}\" for i in range(n_components)]\n",
    "\n",
    "    df_pca_c = pd.DataFrame(c_pca, columns=pc_cols)\n",
    "    df_pca_c[\"AA\"] = c_des[\"AA\"]\n",
    "\n",
    "    df_pca_n = pd.DataFrame(n_pca, columns=pc_cols)\n",
    "    df_pca_n[\"AA\"] = n_des[\"AA\"]\n",
    "\n",
    "    df_pca_uncharged = pd.DataFrame(\n",
    "        uncharged_pca,\n",
    "        columns=pc_cols\n",
    "    )\n",
    "    df_pca_uncharged[\"AA\"] = uncharged_des[\"AA\"]\n",
    "\n",
    "    # -----------------------------\n",
    "    # Build peptide vectors\n",
    "    # -----------------------------\n",
    "\n",
    "    seq_vectors = []\n",
    "\n",
    "    for seq in peptides_df[seq_col]:\n",
    "\n",
    "        vec = []\n",
    "\n",
    "        for i in range(len(seq)):\n",
    "\n",
    "            aa = seq[i]\n",
    "\n",
    "            # N-terminus\n",
    "            if i == 0:\n",
    "                row = df_pca_n.loc[\n",
    "                    df_pca_n[\"AA\"] == aa\n",
    "                ].drop(\"AA\", axis=1)\n",
    "\n",
    "            # C-terminus\n",
    "            elif i == len(seq) - 1:\n",
    "                row = df_pca_c.loc[\n",
    "                    df_pca_c[\"AA\"] == aa\n",
    "                ].drop(\"AA\", axis=1)\n",
    "\n",
    "            # Internal amino acids\n",
    "            else:\n",
    "                row = df_pca_uncharged.loc[\n",
    "                    df_pca_uncharged[\"AA\"] == aa\n",
    "                ].drop(\"AA\", axis=1)\n",
    "\n",
    "            vec.extend(row.values.flatten().tolist())\n",
    "\n",
    "        seq_vectors.append(vec)\n",
    "\n",
    "    # -----------------------------\n",
    "    # Create descriptor dataframe\n",
    "    # -----------------------------\n",
    "\n",
    "    n_features = len(seq_vectors[0])\n",
    "\n",
    "    feature_cols = [f\"v{i}\" for i in range(1, n_features + 1)]\n",
    "\n",
    "    seq_df = pd.DataFrame(seq_vectors, columns=feature_cols)\n",
    "\n",
    "    # Combine with original dataframe\n",
    "    final_df = pd.concat(\n",
    "        [peptides_df.reset_index(drop=True),\n",
    "         seq_df.reset_index(drop=True)],\n",
    "        axis=1\n",
    "    )\n",
    "\n",
    "    return final_df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
