{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8a931d1-5a5c-4dfa-a7c3-867c31348b48",
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_train_test(train_df, test_df, target_col = ''):\n",
    "    X_train = train_df.drop(target_col, axis=1)\n",
    "    y_train = train_df[target_col]\n",
    "    X_test = test_df.drop(target_col, axis=1)\n",
    "    y_test = test_df[target_col]\n",
    "    return X_train, X_test, y_train, y_test\n",
    "\n",
    "def reg_results_df(trained_model, X_train, X_test, y_train, y_test):\n",
    "\n",
    "    #Predictions\n",
    "    y_train_pred = trained_model.predict(X_train).flatten()\n",
    "    y_test_pred = trained_model.predict(X_test).flatten()\n",
    "\n",
    "    #Create train-test labels for the combined table\n",
    "    train_labels = ['Train']*len(y_train_pred)\n",
    "    test_labels = ['Test']*len(y_test_pred)\n",
    "\n",
    "    #Store in dictonary\n",
    "    train_dict = {\n",
    "        'True values': y_train.values,\n",
    "        'Predicted values': y_train_pred,\n",
    "        'Dataset': train_labels\n",
    "    }\n",
    "\n",
    "    test_dict = {\n",
    "        'True values': y_test.values,\n",
    "        'Predicted values': y_test_pred,\n",
    "        'Dataset': test_labels\n",
    "    }\n",
    "\n",
    "    #Combined dataframe with correct index\n",
    "    train_df = pd.DataFrame.from_dict(train_dict).set_index(X_train.index)\n",
    "    test_df = pd.DataFrame.from_dict(test_dict).set_index(X_test.index)\n",
    "\n",
    "    combined_df = pd.concat([train_df, test_df])\n",
    "\n",
    "    return combined_df, train_dict, test_dict\n",
    "\n",
    "def reg_results_plot(combined_df, train_dict, test_dict, padding=10, title=''):\n",
    "    # --- train results ---\n",
    "    y_train = train_dict['True values']\n",
    "    y_train_pred = train_dict['Predicted values']\n",
    "    plot_range = [y_train.min()-1, y_train.max()+1]\n",
    "    r2 = r2_score(y_train, y_train_pred)\n",
    "    train_mae = mean_absolute_error(y_train, y_train_pred)\n",
    "    train_mse = mean_squared_error(y_train, y_train_pred)\n",
    "    # --- test results ---\n",
    "    y_test = test_dict['True values']\n",
    "    y_test_pred = test_dict['Predicted values']\n",
    "    q2 = r2_score(y_test, y_test_pred)\n",
    "    test_mae = mean_absolute_error(y_test, y_test_pred)\n",
    "    test_mse = mean_squared_error(y_test, y_test_pred)\n",
    "\n",
    "    fig, ax = plt.subplots()\n",
    "    ax.set_title(f'{title}')\n",
    "    sns.scatterplot(ax=ax, data=combined_df, x='Predicted values', y='True values', hue='Dataset', legend=False, palette='colorblind')\n",
    "    ax.set_xlim(plot_range)\n",
    "    ax.set_ylim(plot_range)\n",
    "\n",
    "    #plot diagonal\n",
    "    diag_arr = np.arange(plot_range[0], plot_range[1], 0.5)\n",
    "\n",
    "    r2_str = ('%.2f' %r2)\n",
    "    q2_str = ('%.2f' %q2)\n",
    "\n",
    "    train_mae_str = ('%.2f' % train_mae)\n",
    "    test_mae_str = ('%.2f' % test_mae)\n",
    "\n",
    "    train_rmse_str = ('%.2f' % train_mse)\n",
    "    test_rmse_str = ('%.2f' % test_mse)\n",
    "\n",
    "    train_box_str = f\"$R^2$ = {r2_str}\\n\" + \\\n",
    "                    \"$MAE_{train}$\" + \\\n",
    "                    f\" = {train_mae_str}\\n\" + \\\n",
    "                    \"$RMSE_{train}$\" + \\\n",
    "                    f\" = {train_rmse_str}\"\n",
    "    \n",
    "    test_box_str =  f\"$Q^2$ = {q2_str}\\n\" + \\\n",
    "                    \"$MAE_{test}$\" + \\\n",
    "                    f\" = {test_mae_str}\\n\" + \\\n",
    "                    \"$RMSE_{test}$\" + \\\n",
    "                    f\" = {test_rmse_str}\"\n",
    "    \n",
    "    ax.plot(diag_arr, diag_arr, 'k--')\n",
    "\n",
    "    pal = sns.color_palette('colorblind')\n",
    "\n",
    "    ax.text(\n",
    "        y_train.min()*1.1,\n",
    "        y_train.max()*0.9,\n",
    "        train_box_str,\n",
    "        bbox={\n",
    "            'facecolor': pal[0],\n",
    "            'alpha': 0.5,\n",
    "            'pad': padding\n",
    "        },\n",
    "        horizontalalignment = 'center'\n",
    "    )\n",
    "\n",
    "    ax.text(\n",
    "        y_train.max()*0.9,\n",
    "        y_train.min()*1.1,\n",
    "        test_box_str,\n",
    "        bbox={\n",
    "            'facecolor': pal[1],\n",
    "            'alpha': 0.5,\n",
    "            'pad': padding\n",
    "        },\n",
    "        horizontalalignment = 'center'\n",
    "    )\n",
    "\n",
    "    plt.tight_layout()\n",
    "\n",
    "\n",
    "def standard_scaling(train_set, test_set):\n",
    "    scaler = StandardScaler().fit(train_set)\n",
    "    #Scaling the datasets\n",
    "    train_set_scaled = scaler.transform(train_set)\n",
    "    test_set_scaled = scaler.transform(test_set)\n",
    "    #Create dataframes with the correct index\n",
    "    train_set_scaled = pd.DataFrame(train_set_scaled, index=train_set.index, columns=train_set.columns)\n",
    "    test_set_scaled = pd.DataFrame(test_set_scaled, index=test_set.index, columns=test_set.columns)\n",
    "    return train_set_scaled, test_set_scaled\n",
    "\n",
    "def outlier_removal(scaled_train, scaled_test, contamination):\n",
    "    clf = IsolationForest(random_state=42, n_estimators=100, max_samples='auto', contamination=contamination, n_jobs=1).fit(scaled_train)\n",
    "    x_train_outliers = clf.predict(scaled_train) #Returns -1 for outliers and 1 for inliers\n",
    "    x_test_outliers = clf.predict(scaled_test)\n",
    "\n",
    "    X_train_clean = pd.concat([scaled_train, pd.DataFrame(data=x_train_outliers, columns=['Outlier_prediction'], index=scaled_train.index )], axis=1, join='inner' )\n",
    "    X_train_clean = X_train_clean.drop( X_train_clean[X_train_clean['Outlier_prediction'] == -1].index, axis=0) \n",
    "    X_train_clean = X_train_clean.drop('Outlier_prediction', axis=1)  \n",
    "\n",
    "    X_test_clean = pd.concat([scaled_test, pd.DataFrame(data=x_test_outliers, columns=['Outlier_prediction'], index=scaled_test.index )], axis=1, join='inner' )\n",
    "    X_test_clean = X_test_clean.drop( X_test_clean[X_test_clean['Outlier_prediction'] == -1].index, axis=0) \n",
    "    X_test_clean = X_test_clean.drop('Outlier_prediction', axis=1)\n",
    "\n",
    "    n_outliers_train = len(scaled_train) - len(X_train_clean)\n",
    "    n_outliers_test = len(scaled_test) - len(X_test_clean)\n",
    "\n",
    "    print('Performing outlier removal:')\n",
    "\n",
    "    print('the number of outliers for the train set is:', n_outliers_train) \n",
    "    print('the number of outliers for the test set is:', n_outliers_test)\n",
    "    \n",
    "    return X_train_clean, X_test_clean\n",
    "\n",
    "def feature_reduction(train_set, test_set, var_threshold=0.05, corr_threshold=0.8):\n",
    "    print('Number of features originally: ', len(train_set.columns))\n",
    "    print(\"Removing Constant and Nearly Constant Features\")\n",
    "    var_threshold = VarianceThreshold(threshold=var_threshold)\n",
    "    var_threshold.fit(train_set)\n",
    "\n",
    "    indices_features_retained = var_threshold.get_support(indices=True)\n",
    "    train_set_reduced1 = train_set.iloc[:, indices_features_retained]\n",
    "\n",
    "    print('Features retained after elimination of constant and nearly constant features:', len(train_set_reduced1.columns))\n",
    "\n",
    "    print(\"Removing Correlated Features\")\n",
    "\n",
    "    # Calculate the correlation matrix\n",
    "    corr_matrix = train_set_reduced1.corr()\n",
    "    iters = range(len(corr_matrix.columns) - 1)\n",
    "    drop_cols = []\n",
    "\n",
    "    # Iterate through the correlation matrix and compare correlations\n",
    "    for i in iters:\n",
    "        for j in range(i+1):\n",
    "            item = corr_matrix.iloc[j:(j+1), (i+1):(i+2)]\n",
    "            col = item.columns\n",
    "            row = item.index\n",
    "            val = abs(item.values)\n",
    "\n",
    "            # If correlation exceeds the threshold\n",
    "            if val >= corr_threshold:\n",
    "                # Print the correlated features and the correlation value\n",
    "                print(col.values[0], \"|\", row.values[0], \"|\", round(val[0][0], 2))\n",
    "                drop_cols.append(col.values[0])\n",
    "\n",
    "    # Drop one of each pair of correlated columns\n",
    "    drops = set(drop_cols)\n",
    "    train_set_reduced2 = train_set_reduced1.drop(columns=drops)\n",
    "    print('Removed Columns {}'.format(drops))\n",
    "    print('Number of features retained: ', len(train_set_reduced2.columns))\n",
    "\n",
    "    test_set_reduced = test_set[train_set_reduced2.columns]\n",
    "\n",
    "    return train_set_reduced2, test_set_reduced\n",
    "\n",
    "def evaluate_models_random_splits(models_dict, x, y, splits, target,scale):\n",
    "\n",
    "\n",
    "    rows = []\n",
    "\n",
    "    for model_name, base_model in models_dict.items():\n",
    "        # Lists per model\n",
    "        r2_train_list, mae_train_list, rmse_train_list = [], [], []\n",
    "        r2_test_list, mae_test_list, rmse_test_list = [], [], []\n",
    "\n",
    "        for train_idx, test_idx in splits:\n",
    "            # Handle pandas or numpy\n",
    "            if hasattr(x, \"iloc\"):\n",
    "                X_train, X_test = x.iloc[train_idx], x.iloc[test_idx]\n",
    "            else:\n",
    "                X_train, X_test = x[train_idx], x[test_idx]\n",
    "\n",
    "            if hasattr(y, \"iloc\"):\n",
    "                y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]\n",
    "            else:\n",
    "                y_train, y_test = y[train_idx], y[test_idx]\n",
    "\n",
    "            # IMPORTANT: clone the model so each split starts from a fresh estimator\n",
    "            model = clone(base_model)\n",
    "\n",
    "            train_set=pd.concat([X_train, y_train], axis=1)\n",
    "            test_set=pd.concat([X_test, y_test], axis=1)\n",
    "            \n",
    "            #remove correlated features\n",
    "            train_set_reduced2, test_set_reduced = feature_reduction(train_set,test_set, var_threshold=0.05, corr_threshold=0.8)\n",
    "    \n",
    "            #remove outliers\n",
    "            train_clean, test_clean=outlier_removal(train_set_reduced2, test_set_reduced, contamination=0.15)\n",
    "    \n",
    "            #split x,y\n",
    "            X_train=train_clean.drop(target,axis=1)\n",
    "            y_train=train_clean[target]\n",
    "            X_test=test_clean.drop(target,axis=1)\n",
    "            y_test=test_clean[target]\n",
    "\n",
    "            #standard scaling\n",
    "            if scale==True:\n",
    "                X_train,X_test = standard_scaling(X_train, X_test)\n",
    "\n",
    "            # Fit on train\n",
    "            model.fit(X_train, y_train)\n",
    "\n",
    "            # ---- Train metrics ----\n",
    "            y_pred_train = model.predict(X_train)\n",
    "            r2_train = r2_score(y_train, y_pred_train)\n",
    "            mae_train = mean_absolute_error(y_train, y_pred_train)\n",
    "            mse_train = mean_squared_error(y_train, y_pred_train)\n",
    "            rmse_train = np.sqrt(mse_train)\n",
    "\n",
    "            r2_train_list.append(r2_train)\n",
    "            mae_train_list.append(mae_train)\n",
    "            rmse_train_list.append(rmse_train)\n",
    "\n",
    "            # ---- Test metrics (Q2) ----\n",
    "            y_pred_test = model.predict(X_test)\n",
    "            r2_test = r2_score(y_test, y_pred_test)  # Q2\n",
    "            mae_test = mean_absolute_error(y_test, y_pred_test)\n",
    "            mse_test = mean_squared_error(y_test, y_pred_test)\n",
    "            rmse_test = np.sqrt(mse_test)\n",
    "\n",
    "            r2_test_list.append(r2_test)\n",
    "            mae_test_list.append(mae_test)\n",
    "            rmse_test_list.append(rmse_test)\n",
    "\n",
    "            \n",
    "\n",
    "        # After all splits for this model: compute mean & std\n",
    "\n",
    "        # Train row\n",
    "        rows.append({\n",
    "            \"Model\": model_name,\n",
    "            \"Set\": \"Train\",\n",
    "            \"R2_label\": \"R2\",\n",
    "            \"R2_mean\": np.mean(r2_train_list),\n",
    "            \"R2_std\":  np.std(r2_train_list),\n",
    "            \"MAE_mean\": np.mean(mae_train_list),\n",
    "            \"MAE_std\":  np.std(mae_train_list),\n",
    "            \"RMSE_mean\": np.mean(rmse_train_list),\n",
    "            \"RMSE_std\":  np.std(rmse_train_list),\n",
    "        })\n",
    "\n",
    "        # Test row\n",
    "        rows.append({\n",
    "            \"Model\": model_name,\n",
    "            \"Set\": \"Test\",\n",
    "            \"R2_label\": \"Q2\",\n",
    "            \"R2_mean\": np.mean(r2_test_list),\n",
    "            \"R2_std\":  np.std(r2_test_list),\n",
    "            \"MAE_mean\": np.mean(mae_test_list),\n",
    "            \"MAE_std\":  np.std(mae_test_list),\n",
    "            \"RMSE_mean\": np.mean(rmse_test_list),\n",
    "            \"RMSE_std\":  np.std(rmse_test_list),\n",
    "        \n",
    "        })\n",
    "\n",
    "    results_df = pd.DataFrame(rows)\n",
    "    return results_df\n",
    "\n",
    "\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.cross_decomposition import PLSRegression\n",
    "from sklearn.neighbors import KNeighborsRegressor\n",
    "from sklearn.svm import SVR\n",
    "from xgboost import XGBRegressor\n",
    "\n",
    "\n",
    "def run_regression_model(\n",
    "        model_name,\n",
    "        X_train,\n",
    "        X_test,\n",
    "        y_train,\n",
    "        y_test,\n",
    "        cv=5,\n",
    "        scoring=\"r2\",\n",
    "        n_jobs=-1,\n",
    "        verbose=2,\n",
    "        padding=10\n",
    "):\n",
    "    \"\"\"\n",
    "    Train regression model with optional GridSearchCV.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    model_name : str\n",
    "        One of:\n",
    "        'linear'\n",
    "        'random_forest'\n",
    "        'pls'\n",
    "        'xgboost'\n",
    "        'knn'\n",
    "        'svr'\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    fitted_model\n",
    "    combined_df\n",
    "    train_dict\n",
    "    test_dict\n",
    "    \"\"\"\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # Linear Regression\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    if model_name == \"linear\":\n",
    "\n",
    "        model = LinearRegression()\n",
    "\n",
    "        model.fit(X_train, y_train)\n",
    "\n",
    "        combined_df, train_dict, test_dict = reg_results_df(\n",
    "            model,\n",
    "            X_train,\n",
    "            X_test,\n",
    "            y_train,\n",
    "            y_test\n",
    "        )\n",
    "\n",
    "        reg_results_plot(\n",
    "            combined_df,\n",
    "            train_dict,\n",
    "            test_dict,\n",
    "            padding=padding,\n",
    "            title=\"Linear Regression\"\n",
    "        )\n",
    "\n",
    "        return model, combined_df, train_dict, test_dict\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # Random Forest\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"random_forest\":\n",
    "\n",
    "        model = RandomForestRegressor(random_state=0)\n",
    "\n",
    "        param_grid = {\n",
    "            'n_estimators': [100, 200, 300],\n",
    "            'max_depth': [None, 3, 5, 10, 20],\n",
    "            'min_samples_split': [2, 5],\n",
    "            'min_samples_leaf': [1, 2]\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # PLS\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"pls\":\n",
    "\n",
    "        model = PLSRegression()\n",
    "\n",
    "        param_grid = {\n",
    "            'n_components': list(range(1, 21))\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # XGBoost\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"xgboost\":\n",
    "\n",
    "        model = XGBRegressor(\n",
    "            objective='reg:squarederror',\n",
    "            random_state=0\n",
    "        )\n",
    "\n",
    "        param_grid = {\n",
    "            'n_estimators': [100, 150, 200, 300],\n",
    "            'max_depth': [3, 5, 7, 10, 15],\n",
    "            'learning_rate': [0.01, 0.1, 0.2],\n",
    "            'subsample': [0.8, 1.0],\n",
    "            'colsample_bytree': [0.8, 1.0]\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # KNN\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"knn\":\n",
    "\n",
    "        model = KNeighborsRegressor()\n",
    "\n",
    "        param_grid = {\n",
    "            'n_neighbors': [3, 5, 7, 9, 11],\n",
    "            'weights': ['uniform', 'distance'],\n",
    "            'p': [1, 2]\n",
    "        }\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # SVR\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    elif model_name == \"svr\":\n",
    "\n",
    "        model = SVR()\n",
    "\n",
    "        param_grid = {\n",
    "            'C': [0.1, 1, 10],\n",
    "            'epsilon': [0.01, 0.1, 1],\n",
    "            'kernel': ['rbf', 'linear'],\n",
    "            'gamma': ['scale', 'auto']\n",
    "        }\n",
    "\n",
    "    else:\n",
    "        raise ValueError(f\"Unknown model_name: {model_name}\")\n",
    "\n",
    "    # -------------------------------------------------\n",
    "    # GridSearchCV\n",
    "    # -------------------------------------------------\n",
    "\n",
    "    grid_search = GridSearchCV(\n",
    "        estimator=model,\n",
    "        param_grid=param_grid,\n",
    "        scoring=scoring,\n",
    "        cv=cv,\n",
    "        n_jobs=n_jobs,\n",
    "        verbose=verbose\n",
    "    )\n",
    "\n",
    "    grid_search.fit(X_train, y_train)\n",
    "\n",
    "    best_model = grid_search.best_estimator_\n",
    "\n",
    "    print(\"Best model:\")\n",
    "    print(best_model)\n",
    "\n",
    "    print(\"\\nBest parameters:\")\n",
    "    print(grid_search.best_params_)\n",
    "\n",
    "    combined_df, train_dict, test_dict = reg_results_df(\n",
    "        grid_search,\n",
    "        X_train,\n",
    "        X_test,\n",
    "        y_train,\n",
    "        y_test\n",
    "    )\n",
    "\n",
    "    reg_results_plot(\n",
    "        combined_df,\n",
    "        train_dict,\n",
    "        test_dict,\n",
    "        padding=padding,\n",
    "        title=f\"{model_name.upper()} GridSearchCV\"\n",
    "    )\n",
    "\n",
    "    return best_model, combined_df, train_dict, test_dict"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
